[package]
name = "garc"
version = "0.1.0"
authors = ["MarimeGui <lepro.guillaume@gmail.com>"]
edition = "2018"

[dependencies]
ez_io = { git = "https://github.com/MarimeGui/ez_io.git" }
clap = "2.33.0"